# Generated by Django 5.1.4 on 2026-07-01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NutritionIntake",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("preferred_meal_count", models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ("dietary_style", models.CharField(choices=[("none", "No specific style"), ("vegetarian", "Vegetarian"), ("vegan", "Vegan"), ("pescatarian", "Pescatarian"), ("low_carb", "Low carb"), ("other", "Other")], max_length=24)),
                ("cooking_time", models.CharField(choices=[("under_15", "Under 15 minutes"), ("15_30", "15 to 30 minutes"), ("30_60", "30 to 60 minutes"), ("over_60", "Over 60 minutes")], max_length=16)),
                ("budget_level", models.CharField(choices=[("economical", "Economical"), ("moderate", "Moderate"), ("flexible", "Flexible")], max_length=16)),
                ("eating_out_frequency", models.CharField(choices=[("rarely", "Rarely"), ("weekly_1_2", "1 to 2 times weekly"), ("weekly_3_5", "3 to 5 times weekly"), ("daily", "Daily")], max_length=16)),
                ("food_allergies", models.TextField(blank=True, default="", max_length=500)),
                ("disliked_foods", models.TextField(blank=True, default="", max_length=500)),
                ("completed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="nutrition_intake", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="WorkoutIntake",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("workout_location", models.CharField(choices=[("home", "Home"), ("gym", "Gym"), ("outdoor", "Outdoor"), ("mixed", "Mixed")], max_length=16)),
                ("available_days_per_week", models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ("session_duration_minutes", models.PositiveSmallIntegerField(choices=[(20, "20"), (30, "30"), (45, "45"), (60, "60"), (90, "90")])),
                ("experience_level", models.CharField(choices=[("beginner", "Beginner"), ("intermediate", "Intermediate"), ("advanced", "Advanced")], max_length=16)),
                ("equipment_access", models.CharField(choices=[("none", "No equipment"), ("basic", "Basic equipment"), ("full_gym", "Full gym")], max_length=16)),
                ("preferred_workout_style", models.CharField(choices=[("no_preference", "No preference"), ("strength", "Strength"), ("cardio", "Cardio"), ("mobility", "Mobility"), ("mixed", "Mixed")], max_length=20)),
                ("injuries_or_limitations", models.TextField(blank=True, default="", max_length=1000)),
                ("completed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="workout_intake", to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
