# Generated by Django 5.2.15 on 2026-07-02 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('nutrition', 'Nutrition'), ('workout', 'Workout')], max_length=16)),
                ('source', models.CharField(choices=[('self', 'Self'), ('coach', 'Coach'), ('admin', 'Admin'), ('external_specialist', 'External specialist'), ('system_future', 'Future system')], max_length=24)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='active', max_length=16)),
                ('title', models.CharField(max_length=120)),
                ('notes', models.TextField(max_length=5000)),
                ('external_provider_name', models.CharField(blank=True, default='', max_length=120)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plans', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['owner', 'plan_type', 'status'], name='plans_plan_owner_i_4e1775_idx'), models.Index(fields=['owner', 'updated_at'], name='plans_plan_owner_i_5c96aa_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_on__isnull', True), ('starts_on__isnull', True), ('ends_on__gte', models.F('starts_on')), _connector='OR'), name='plan_dates_in_order')],
            },
        ),
    ]
