# Generated by Django 5.2.15 on 2026-07-02 12:25

import plans.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=plans.models.plan_attachment_upload_to),
        ),
        migrations.AddField(
            model_name='plan',
            name='attachment_content_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='plan',
            name='attachment_original_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='plan',
            name='attachment_size',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
